# Generated by Django 5.1.7 on 2025-03-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_alter_artist_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.ImageField(default=1, upload_to="artists_cards"),
            preserve_default=False,
        ),
    ]
