# Generated by Django 5.1.7 on 2025-03-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_alter_playlist_image_alter_track_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="music.artist"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
