# Generated by Django 5.1.7 on 2025-03-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_track_artist_alter_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='music.track'),
        ),
    ]
