# Generated by Django 5.1.7 on 2025-04-23 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0010_playlist_is_liked_playlist_alter_playlist_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-04-22 09:56:34.096715"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="album",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Черновик"), ("Published", "Опубликован")], default="Draft", max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="title",
            field=models.CharField(default="favorite", max_length=128, unique=True, verbose_name="Мне нравится"),
        ),
        migrations.AlterUniqueTogether(
            name="playlist",
            unique_together={("owner", "is_liked_playlist", "title")},
        ),
    ]
