# Generated by Django 5.1.7 on 2025-04-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_playlist_unique_together_album_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-22 09:56:34.096715'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликован')], default='DR', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
