# Generated by Django 5.2 on 2025-04-25 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_track_create_at_alter_album_status_alter_track_album_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликован')], default='DR', max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='albums_images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(upload_to='albums_images/'),
        ),
    ]
