# Generated by Django 5.2 on 2025-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_rename_create_at_track_created_at_album_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='in_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен')], default='in_pending', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='in_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен'), ('PB', 'Опубликован')], default='in_pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен'), ('PB', 'Опубликован')], default='in_pending', max_length=10),
        ),
    ]
