# Generated by Django 5.2 on 2025-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_album_in_pending_artist_status_track_in_pending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='in_pending',
        ),
        migrations.RemoveField(
            model_name='track',
            name='in_pending',
        ),
        migrations.AddField(
            model_name='album',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен')], default='in_pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен')], default='in_pending', max_length=10),
        ),
    ]
